"""
Django settings for Timetable project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

if os.getenv('BUILD_ON_TRAVIS',None):
    SECRET_KEY="SecretKeyForUseOnTravis"
    DEBUG = False
    TEMPLATE_DEBUG = False

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'travis_ci_db',
            'USER': 'travis',
            'PASSWORD': '',
            'HOST': '127.0.0.1',
        }
    }
else:

   # Build paths inside the project like this: os.path.join(BASE_DIR, ...)
   BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


   # Quick-start development settings - unsuitable for production
   # See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

   # SECURITY WARNING: keep the secret key used in production secret!
   SECRET_KEY = '(z%$k@q!l%z_wvm=c@%xv+mukrv+sk_^z4(^&$rmkad*)lf0s7'

   # SECURITY WARNING: don't run with debug turned on in production!
   DEBUG = False

   ALLOWED_HOSTS = ['*']

   STATICFILES_DIRS=[os.path.join(BASE_DIR,"static"),'Timetable Generator/timetable-generator/Timetable/Register/templates/Register/static/css/']
   # Application definition

   INSTALLED_APPS = [

      # 'Class.apps.ClassConfig',
      #  'Announcements.apps.AnnouncementsConfig',
      #  'Courses.apps.CoursesConfig',
       'Lecturer',
       'Register',
       'django.contrib.admin',
       'django.contrib.auth',
       'django.contrib.contenttypes',
       'django.contrib.sessions',
       'django.contrib.messages',
       'django.contrib.staticfiles',
   ]
   TEST_RUNNER = 'django_nose.NoseTestSuiteRunner'

    NOSE_ARGS =[

        '--cover-erase',
        '--with-coverage',
        '--cover-package=Register',
        '--cover-html',

    ]
 
   MIDDLEWARE = [
       'django.middleware.security.SecurityMiddleware',
       'django.contrib.sessions.middleware.SessionMiddleware',
       'django.middleware.common.CommonMiddleware',
       'django.middleware.csrf.CsrfViewMiddleware',
       'django.contrib.auth.middleware.AuthenticationMiddleware',
       'django.contrib.messages.middleware.MessageMiddleware',
       'django.middleware.clickjacking.XFrameOptionsMiddleware',
   ]

   ROOT_URLCONF = 'Timetable.urls'

   TEMPLATES = [
       {
           'BACKEND': 'django.template.backends.django.DjangoTemplates',
           'DIRS': [],
           'APP_DIRS': True,
           'OPTIONS': {
               'context_processors': [
                   'django.template.context_processors.debug',
                   'django.template.context_processors.request',
                   'django.contrib.auth.context_processors.auth',
                   'django.contrib.messages.context_processors.messages',
               ],
           },
       },
   ]

   WSGI_APPLICATION = 'Timetable.wsgi.application'


   # Database
   # https://docs.djangoproject.com/en/2.1/ref/settings/#databases

   DATABASES = {
       'default': {
           'ENGINE': 'django.db.backends.sqlite3',
           'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
       }
   }


   # Password validation
   # https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

   AUTH_PASSWORD_VALIDATORS = [
       {
           'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
       },
       {
           'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
       },
       {
           'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
       },
       {
           'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
       },
   ]


   # Internationalization
   # https://docs.djangoproject.com/en/2.1/topics/i18n/

   LANGUAGE_CODE = 'en-us'

   TIME_ZONE = 'Greenwich'

   USE_I18N = True

   USE_L10N = True

   USE_TZ = True


   # Static files (CSS, JavaScript, Images)
   # https://docs.djangoproject.com/en/2.1/howto/static-files/

   STATIC_URL = '/static/'
