# Generated by Django 2.1.7 on 2019-03-29 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_auto_20190325_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredStaff',
            fields=[
                ('Staff_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Course_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredStds',
            fields=[
                ('Std_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Course_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.Courses')),
            ],
        ),
    ]
