# Generated by Django 2.1.7 on 2019-04-07 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0006_auto_20190407_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredstaffs',
            name='Course_Code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.Courses'),
        ),
    ]
