# Generated by Django 2.1.7 on 2019-05-15 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0008_auto_20190408_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredstaffs',
            name='Course_Code',
        ),
        migrations.DeleteModel(
            name='RegisteredStaffs',
        ),
    ]
