# Generated by Django 2.2 on 2019-05-23 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0010_auto_20190516_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='Course_Code',
        ),
        migrations.RemoveField(
            model_name='class',
            name='Lect_No',
        ),
        migrations.RemoveField(
            model_name='class',
            name='Student_No',
        ),
        migrations.RemoveField(
            model_name='login',
            name='Student_No',
        ),
        migrations.DeleteModel(
            name='Announcements',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Lecturer',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='StudentsRegister',
        ),
    ]
