# Generated by Django 2.2.1 on 2019-05-29 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Register', '0011_auto_20190523_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_No', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('CellPhone_No', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.IntegerField()),
                ('Student_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.StudentsRegister')),
            ],
        ),
    ]
