# Generated by Django 2.1.7 on 2019-05-16 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredstaffs',
            name='Course_Code',
        ),
        migrations.RemoveField(
            model_name='registeredstd',
            name='Course_Code',
        ),
        migrations.DeleteModel(
            name='StudentsRegister',
        ),
        migrations.DeleteModel(
            name='RegisteredStaffs',
        ),
        migrations.DeleteModel(
            name='RegisteredStd',
        ),
    ]
