# Generated by Django 2.2.1 on 2019-05-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_auto_20190529_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='Course_Venue',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
