# Generated by Django 2.1.7 on 2019-03-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0003_registeredstaff_registeredstds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredstaff',
            name='Course_Code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registeredstds',
            name='Course_Code',
            field=models.CharField(max_length=100),
        ),
    ]
