# Generated by Django 2.1.7 on 2019-05-16 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_auto_20190516_0524'),
        ('Log_In', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredStd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Std_no', models.IntegerField(max_length=100)),
                ('Course_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RegisteredStd', to='Courses.Courses')),
            ],
        ),
        migrations.AlterField(
            model_name='registeredstaffs',
            name='Course_Code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.Courses'),
        ),
    ]
