# Generated by Django 2.2 on 2019-05-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log_In', '0002_auto_20190516_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='once',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Std_no', models.IntegerField(max_length=100)),
            ],
        ),
    ]
