# Generated by Django 2.2 on 2019-05-23 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Log_In', '0003_once'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredstd',
            name='Course_Code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.Courses'),
        ),
    ]
