# Generated by Django 2.2 on 2019-05-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log_In', '0004_auto_20190523_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredstd',
            name='Course_Code',
            field=models.CharField(max_length=100),
        ),
    ]
