# Generated by Django 2.2 on 2019-05-25 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Log_In', '0005_auto_20190524_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsregister',
            name='CellPhone_No',
        ),
    ]
